# Generated by Django 5.0.3 on 2024-03-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='urls',
            fields=[
                ('shortURL', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('mainURL', models.CharField(max_length=500)),
            ],
        ),
    ]
